### ISSUE TITLE
can't migrate vm

### ISSUE THREAD

**Issue by ahmedelsayed-93** [0-complexity/openvcloud#1113]
#### Detailed description
```
ServiceUnavailable: 503: Service Unavailable "Could not perform action: vm_livemigrate at this time"
```
#### Steps to reproduce
- create vm
- migrate vm

#### Relevant stacktraces

```
/opt/jumpscale7/libext/CloudscalerLibcloud/compute/drivers/libvirt_driver.py
```
```
  worker.py(line 279) (function <module>)
  ========== STACKFRAME==========
        opts = parser.parse_args()
    
        j.application.instanceconfig = j.application.getAppInstanceHRD(name="jsagent", instance=opts.instance)
    
        j.core.osis.client = j.clients.osis.getByInstance(die=False)
    
        j.application.start("jumpscale:worker:%s" % opts.queuename)
    
        if j.application.config.exists("grid.id"):
            j.application.initGrid()
    
        j.logger.consoleloglevel = 2
        j.logger.maxlevel = 7
    
        worker = Worker(opts.queuename, opts.logpath)
-->     worker.run()
  ============ LOCALS============
    RedisWorkerFactory : <class 'JumpScale.baselib.redisworker.RedisWorker.RedisWorkerFactory'>
    WORKERTIMEOUTS : {'default': 300, 'process': 300, 'io': 3600, 'hypervisor': 300}
    Worker : <class '__main__.Worker'>
    j : <JumpScale.JumpScale object at 0x7f01ccbc46d0>
    opts : Namespace(instance='main', logpath='/opt/jumpscale7/var/log/processmanager/logs/workers_hypervisor_main.log', queuename='hypervisor')
    parser : ArgumentParser(prog='worker.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
    worker : <__main__.Worker object at 0x7f01ab02a910>
  
------------------------------------------------------------------------------------------
  worker.py(line 171) (function run)
  ========== STACKFRAME==========
                        if status is True:
                            job.result=result
                            job.state="OK"
                            job.resultcode=0
                        else:
                            if isinstance(result, basestring):
                                job.state = result
                            else:
-->                             eco = j.errorconditionhandler.getErrorConditionObject(ddict=result)
                                agentid=j.application.getAgentId()
                                msg="Could not execute jscript:%s %s_%s on agent:%s\nError: %s"%(jscript.id,jscript.organization,jscript.name,agentid, eco.errormessage)
                                eco.errormessage = msg
                                eco.jid = job.guid
                                eco.code=jscript.source
                                eco.category = "workers.executejob"
    
  ============ LOCALS============
    agentid : 107_2
    job : {
  "_ckey": "", 
  "_meta": [
    "system", 
    "job", 
    1
  ], 
  "achost": "10.107.2.1", 
  "args": {
    "domainxml": " <domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>\n        <name>vm-512</name>\n        <uuid>27d4d585-1388-4b8a-b429-c4c563485c9d</uuid>\n        <maxMemory slots='16' unit='MiB'>253812</maxMemory>\n        \n        <currentMemory unit='MiB'>512</currentMemory>\n        <cpu>\n          <numa>\n              <cell id='0' cpus='0-0' memory='512' unit='MiB'/>\n          </numa>\n        </cpu>\n        <vcpu placement='static' current='1'>255</vcpu>\n        \n        <os>\n            <type arch='x86_64' machine='ubuntu'>hvm</type>\n            <boot dev='hd'/>\n        </os>\n        <features>\n            <acpi/>\n            <apic/>\n            <pae/>\n            \n        </features>\n        \n        <clock offset='utc'/>\n        \n        <on_poweroff>destroy</on_poweroff>\n        <on_reboot>restart</on_reboot>\n        <on_crash>restart</on_crash>\n        <devices>\n            <emulator>/usr/bin/qemu-system-x86_64</emulator>\n            \n            <disk type='network' device='disk'>\n    <driver name='qemu' type='raw' cache='none' io='threads'/>\n    <source protocol='openvstorage' name='vm-512/bootdisk-vm-512' vdiskguid='181c57d5-6c36-4353-b707-3f5d880ce4cd'\n    \n    username='edgeUser01' passwd='xaep0dooV8ughoo0'\n    \n    >\n        <host name='10.107.3.42' port='26203' transport='tcp'/>\n    </source>\n\n    <iotune>\n     \n     <total_iops_sec>2000</total_iops_sec>\n     \n     \n    </iotune>\n\n    <target dev='vda' bus='virtio'/>\n</disk>\n            \n            <disk type='network' device='cdrom'>\n    <driver name='qemu' type='raw' cache='none' io='threads'/>\n    <source protocol='openvstorage' name='vm-512/cloud-init-vm-512' vdiskguid='ec20ec2c-2b72-4524-84da-a265297a08c9'\n    \n    username='edgeUser01' passwd='xaep0dooV8ughoo0'\n    \n    >\n        <host name='10.107.3.42' port='26203' transport='tcp'/>\n    </source>\n\n    <target dev='hdc' bus='ide'/>\n</disk>\n            \n            <controller type='usb' index='0'>\n                <alias name='usb0'/>\n                <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>\n            </controller>\n            <controller type='ide' index='0'>\n                <alias name='ide0'/>\n                <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>\n            </controller>\n            \n                        <interface type='network'>\n                <source network='space_00d1'/>\n                <mac address='52:54:00:00:01:76'/>\n                <target dev='vm-512-00d1' />\n                <model type='virtio'/>\n                <bandwidth>\n                  <inbound average='134218' peak='134218' burst='134218'/>\n                  <outbound average='134218' peak='134218' burst='134218'/>\n                </bandwidth>\n            </interface>\n            \n            <serial type='pty'>\n                <source path='/dev/pts/1'/>\n                <target port='0'/>\n                <alias name='serial0'/>\n            </serial>\n            <console type='pty' tty='/dev/pts/1'>\n                <source path='/dev/pts/1'/>\n                <target type='serial' port='0'/>\n                <alias name='serial0'/>\n            </console>\n\t    <input type='mouse' bus='ps2'/>\n\t    <input type='tablet' bus='usb'/>\n            <graphics type='vnc' autoport='yes' listen='0.0.0.0'>\n                <listen type='address' address='0.0.0.0'/>\n            </graphics>\n            <video>\n                <model type='cirrus' vram='9216' heads='1'/>\n                <alias name='video0'/>\n                <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>\n            </video>\n            <memballoon model='virtio'>\n                <alias name='balloon0'/>\n                <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>\n            </memballoon>\n        </devices>\n </domain>", 
    "force": false, 
    "sourceurl": "qemu+ssh://10.107.1.19/system", 
    "vm_id": "27d4d585-1388-4b8a-b429-c4c563485c9d"
  }, 
  "category": "greenitglobe", 
  "cmd": "vm_livemigrate", 
  "errorreport": false, 
  "gid": 107, 
  "guid": "6123265530904958833cae1f5b32a48d", 
  "id": 42557, 
  "internal": false, 
  "jscriptid": 61, 
  "log": true, 
  "nid": 2, 
  "parent": null, 
  "queue": "hypervisor", 
  "result": null, 
  "resultcode": null, 
  "roles": [], 
  "sessionid": "107_1_0_bbfb4a34-e95e-4f0a-966e-fbc357a23ba0", 
  "state": "STARTED", 
  "timeCreate": 1513591249, 
  "timeStart": 1513591249.468817, 
  "timeStop": 0, 
  "timeout": 600, 
  "wait": true
}
    jscript : <JumpScale.grid.jumpscripts.JumpscriptFactory.Jumpscript object at 0x7f01ab052bd0>
    jskey : (u'greenitglobe', u'vm_livemigrate')
    jtype : job
    line : 
    msg : Could not execute jscript:61 greenitglobe_vm_livemigrate on agent:107_2
Error: 
    result : Traceback (most recent call last):
    return True, self.module.action(*args, **kwargs)
~   File "/tmp/jumpscripts/greenitglobe_vm_livemigrate.py", line 39, in action
    domain.migrate2(target_con, flags=flags, uri=targeturl)
~   File "/usr/lib/python2.7/dist-packages/libvirt.py", line 1622, in migrate2
    if ret is None:raise libvirtError('virDomainMigrate2() failed', dom=self)
~ libvirtError: unsupported configuration: Unable to find security driver for model apparmor

type/level: OPERATIONS/1
Exec error procmgr jumpscr:greenitglobe_vm_livemigrate on node:107_2 <class 'libvirt.libvirtError'>: unsupported configuration: Unable to find security driver for model apparmor

    self : <__main__.Worker object at 0x7f01ab02a910>
  
------------------------------------------------------------------------------------------
  /opt/jumpscale7/lib/JumpScale/core/errorhandling/ErrorConditionHandler.py(line 248) (function getErrorConditionObject)
  ========== STACKFRAME==========
            return eco
    
        def getErrorConditionObject(self,ddict={},msg="",msgpub="",category="",level=1,type="UNKNOWN",tb=None, noreraise=False):
            """
            @data is dict with fields of errorcondition obj
            returns only ErrorConditionObject which should be used in jumpscale to define an errorcondition (or potential error condition)
    
            """
-->         errorconditionObject= ErrorConditionObject(ddict=ddict,msg=msg,msgpub=msgpub,level=level,category=category,type=type,tb=tb)
            errorconditionObject.noreraise = noreraise
            return errorconditionObject
    
        def processPythonExceptionObject(self,pythonExceptionObject,ttype=None, tb=None,level=1,message="",sentry=True):
            """
            how to use
    
  ============ LOCALS============
    category : 
    ddict : Traceback (most recent call last):
    return True, self.module.action(*args, **kwargs)
~   File "/tmp/jumpscripts/greenitglobe_vm_livemigrate.py", line 39, in action
    domain.migrate2(target_con, flags=flags, uri=targeturl)
~   File "/usr/lib/python2.7/dist-packages/libvirt.py", line 1622, in migrate2
    if ret is None:raise libvirtError('virDomainMigrate2() failed', dom=self)
~ libvirtError: unsupported configuration: Unable to find security driver for model apparmor

type/level: OPERATIONS/1
Exec error procmgr jumpscr:greenitglobe_vm_livemigrate on node:107_2 <class 'libvirt.libvirtError'>: unsupported configuration: Unable to find security driver for model apparmor

    msg : 
    msgpub : 
    self : <JumpScale.core.errorhandling.ErrorConditionHandler.ErrorConditionHandler instance at 0x7f01ca75bd40>
    tb : None
    type : UNKNOWN
  
------------------------------------------------------------------------------------------
  /opt/jumpscale7/lib/JumpScale/core/errorhandling/ErrorConditionObject.py(line 33) (function __init__)
  ========== STACKFRAME==========
                self.__dict__ = ddict
            else:
    
                self.backtrace = ""
                self.backtraceDetailed = ""
                btkis, filename0, linenr0, func0 = j.errorconditionhandler.getErrorTraceKIS(tb=tb)
    
                if len(btkis) > 1:
-->                 self.backtrace = self.getBacktraceDetailed(tb)
                    self.backtraceDetailed = self.backtrace
    
                self.category = category  # is category in dot notation
                self.errormessage = msg
                self.errormessagePub = msgpub
                self.level = int(level)  # 1:critical, 2:warning, 3:info see j.enumerators.ErrorConditionLevel.
                self.data = data
  ============ LOCALS============
    category : 
    data : None
    ddict : Traceback (most recent call last):
    return True, self.module.action(*args, **kwargs)
~   File "/tmp/jumpscripts/greenitglobe_vm_livemigrate.py", line 39, in action
    domain.migrate2(target_con, flags=flags, uri=targeturl)
~   File "/usr/lib/python2.7/dist-packages/libvirt.py", line 1622, in migrate2
    if ret is None:raise libvirtError('virDomainMigrate2() failed', dom=self)
~ libvirtError: unsupported configuration: Unable to find security driver for model apparmor

type/level: OPERATIONS/1
Exec error procmgr jumpscr:greenitglobe_vm_livemigrate on node:107_2 <class 'libvirt.libvirtError'>: unsupported configuration: Unable to find security driver for model apparmor

    filename0 : worker.py
    func0 : run
    msg : 
    msgpub : 
    tb : None
    type : UNKNOWN
  
------------------------------------------------------------------------------------------
  /opt/jumpscale7/lib/JumpScale/core/errorhandling/ErrorConditionObject.py(line 271) (function getBacktraceDetailed)
  ========== STACKFRAME==========
            import inspect
            if j.application.skipTraceback:
                return ""
            sep = "\n" + "-" * 90 + "\n"
            result = ''
            if tracebackObject is None:
                if frame is None:
                    frame = inspect.currentframe()
-->             frames = inspect.getouterframes(frame, 16)[::-1]
            else:
                frames = inspect.getinnerframes(tracebackObject, 16)
            frames = frames[startframe:]
            for (frame, filename, lineno, fun, context, idx) in frames[-framecount:]:
                location = filename + "(line %d) (function %s)\n" % (lineno, fun)
                if location.find("EventHandler.py") == -1:
                    result += "  " + sep
  ============ LOCALS============
    context : ['        import inspect\n', '        if j.application.skipTraceback:\n', '            return ""\n', '        sep = "\\n" + "-" * 90 + "\\n"\n', "        result = ''\n", '        if tracebackObject is None:\n', '            if frame is None:\n', '                frame = inspect.currentframe()\n', '            frames = inspect.getouterframes(frame, 16)[::-1]\n', '        else:\n', '            frames = inspect.getinnerframes(tracebackObject, 16)\n', '        frames = frames[startframe:]\n', '        for (frame, filename, lineno, fun, context, idx) in frames[-framecount:]:\n', '            location = filename + "(line %d) (function %s)\\n" % (lineno, fun)\n', '            if location.find("EventHandler.py") == -1:\n', '                result += "  " + sep\n']
    filename : /opt/jumpscale7/lib/JumpScale/core/errorhandling/ErrorConditionObject.py
    frame : <frame object at 0x1d91570>
    fun : getBacktraceDetailed
    k : type
    line :                 result += "  " + sep

    location : /opt/jumpscale7/lib/JumpScale/core/errorhandling/ErrorConditionObject.py(line 271) (function getBacktraceDetailed)

    prefix :     
    sep : 
------------------------------------------------------------------------------------------

    tracebackObject : None
    v : UNKNOWN


```

#### Installation information
be-g8-3
JumpScale

    Core: branch: master (a166a21) 12/17/2017, 2:27:29 PM
    Portal: branch: master (30066b4) 12/13/2017, 10:39:40 PM

OpenvCloud

    Core: branch: master (aa86fa4) 12/18/2017, 8:52:52 AM
    G8VDC: branch: master (ea4dc79) 12/14/2017, 9:33:18 AM
    Selfhealing: branch: master (d0a4bc5) 12/17/2017, 11:25:08 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1

**Comment by grimpy** [comment]
Related to environment but could be hardened in code, apprently you have certain nodes with apparmor enabled and certain without.

**Comment by FastGeert** [comment]
Due to automated installation procedure of lesser importance

**Comment by dinosn** [comment]
We still face the issue on several systems and the problem prevents vms from being migrated / moved from node to node.

**Comment by islamTaha12** [comment]
```
JumpScale
Core: branch: master (95e24e7) 27/02/2018, 16:26:50
Portal: branch: master (29a3df6) 21/02/2018, 15:52:30
OpenvCloud
Core: branch: master (f89698e) 27/02/2018, 22:22:18
G8VDC: branch: master (d4b49c1) 13/02/2018, 13:56:43
Selfhealing: branch: master (bdaf210) 28/02/2018, 08:46:33
OpenvStorage be-g8-3
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
```
