### ISSUE TITLE
Fix bond name in networkbond_check script

### ISSUE THREAD

**Issue by PeterNashaat** [0-complexity/openvcloud#1309]
#### Detailed description
we get error if the bond name doesn't start with " bond- "

#### Steps to reproduce

- create the bond with no " bond- " in the name 
```
gig@b17-ctrl-01:~$ sudo ovs-appctl bond/show
---- bkplnbond ----
bond_mode: active-backup
bond may use recirculation: no, Recirc-ID : -1
bond-hash-basis: 0
updelay: 0 ms
downdelay: 0 ms
lacp_status: off
active slave mac: 0c:c4:7a:9b:fc:95(eno2)

slave eno1: enabled
	may_enable: true

slave eno2: enabled
	active slave
	may_enable: true
```

- run networkbond_check 

```
root@b17-ctrl-01:~# jspython /opt/jumpscale7/apps/processmanager/jumpscripts/healthchecks/networkbond_check.py
Traceback (most recent call last):
~   File "/opt/jumpscale7/apps/processmanager/jumpscripts/healthchecks/networkbond_check.py", line 63, in <module>
    print(yaml.dump(action(), default_flow_style=False))
~   File "/opt/jumpscale7/apps/processmanager/jumpscripts/healthchecks/networkbond_check.py", line 55, in action
    msg = 'Bond: {}, all slave are ok'.format(bond['name'])
~ KeyError: 'name'

type/level: UNKNOWN/1
KeyError: name
```
#### Installation information

- environment version: b17
- operating system: linux
- portal verison production
- ovc version production

**Comment by FastGeert** [comment]
Feel free to provide a PR @PeterNashaat
