### ISSUE TITLE
POST /cloudbroker/image/createCDROMImage raise internal server error

### ISSUE THREAD

**Issue by islamTaha12** [0-complexity/openvcloud#1374]
#### Detailed description
POST /cloudbroker/image/createCDROMImage API riase an internal server error.

#### Steps to reproduce
![image](https://user-images.githubusercontent.com/17981089/36672074-a1d94278-1b06-11e8-9a72-fec8547542ee.png)

**Expected result**
bad request

#### Installation information
```
JumpScale
Core: branch: master (278c4fb) 21/02/2018, 13:43:54
Portal: branch: master (29a3df6) 21/02/2018, 15:52:30
OpenvCloud
Core: branch: master (81debe4) 22/02/2018, 14:27:21
G8VDC: branch: master (d4b49c1) 13/02/2018, 13:56:43
Selfhealing: branch: master (ac36bf5) 21/02/2018, 15:09:31
OpenvStorage be-g8-4
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.9-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.9-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.17
openvstorage: 2.9.9-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.1-1
openvstorage-sdm: 1.9.1-1
```

**Comment by grimpy** [comment]
```
***ERROR***:Traceback (most recent call last):
~   File "/opt/jumpscale7/lib/JumpScale/portal/portal/PortalRest.py", line 254, in execute_rest_call
    result = method(ctx=ctx, **ctx.params)
~   File "/opt/jumpscale7/lib/JumpScale/portal/portal/auth.py", line 96, in wrapper
    return func(*args, **kwargs)
~   File "/opt/jumpscale7/apps/portals/main/base/cloudbroker__image/methodclass/cloudbroker_image.py", line 151, in createCDROMImage
    bytesize = self._getImageSize(url)
~   File "/opt/jumpscale7/apps/portals/main/base/cloudbroker__image/methodclass/cloudbroker_image.py", line 62, in _getImageSize
    resp = requests.head(url)
~   File "/opt/jumpscale7/lib/requests/api.py", line 93, in head
    return request('head', url, **kwargs)
~   File "/opt/jumpscale7/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
~   File "/opt/jumpscale7/lib/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
~   File "/opt/jumpscale7/lib/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
~   File "/opt/jumpscale7/lib/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
~   File "/opt/jumpscale7/lib/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
~ MissingSchema: Invalid URL 'test': No schema supplied. Perhaps you meant http://test?
type/level: UNKNOWN/1
MissingSchema: Invalid URL 'test': No schema supplied. Perhaps you meant http://test?
Execute method POST_cloudbroker_image_createCDROMImage failed.
method was:/restmachine/cloudbroker/image/createCDROMImage
 : method /restmachine/cloudbroker/image/createCDROMImage from ip 10.244.1.198 with params
```

**Comment by Dinaamagdy** [comment]
still return 500 as shown
![selection_646](https://user-images.githubusercontent.com/24386802/36723438-e5f31210-1bb8-11e8-8ce0-27fa639131de.png)
![selection_647](https://user-images.githubusercontent.com/24386802/36723442-e96b1bea-1bb8-11e8-837a-6f3be7cbe3a2.png)
## Software Version
```
JumpScale
Core: branch: master (278c4fb) 2/21/2018, 1:43:54 PM
Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM
OpenvCloud
Core: branch: master (81debe4) 2/22/2018, 2:27:21 PM
G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
Selfhealing: branch: master (ac36bf5) 2/21/2018, 3:09:31 PM

```

**Comment by grimpy** [comment]
This wasnt live on QA env yet should be available for testin on be-g8-3

**Comment by ahmedelsayed-93** [comment]
verified on be-g8-3

### software version 

JumpScale

    Core: branch: master (95e24e7) 2/27/2018, 4:26:50 PM
    Portal: branch: master (29a3df6) 2/21/2018, 3:52:30 PM

OpenvCloud

    Core: branch: master (f89698e) 2/27/2018, 10:22:18 PM
    G8VDC: branch: master (d4b49c1) 2/13/2018, 1:56:43 PM
    Selfhealing: branch: master (bdaf210) 2/28/2018, 8:46:33 AM

OpenvStorage be-g8-3

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.0-1
    openvstorage-webapps: 2.9.9-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.9-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.17
    openvstorage: 2.9.9-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.1-1
    openvstorage-sdm: 1.9.1-1
