### ISSUE TITLE
Putting node on maintenance mode : error comes up when move a ROS to a destination cpu, the destination CPU already has an exist snapshot

### ISSUE THREAD

**Issue by Pishoy** [0-complexity/openvcloud#1440]
#### Detailed description

got error when putting a cpu node on maintenance mode while node contains a ROS
the destination cpu node has already a snapshot to this ROS 

#### Steps to reproduce
1- take a snapshot to ROS on cpu node CPU-01
2- move this ROS to CPU-05 
3- move back this ROS to CPU-01

solved by removing snapshot on correct directory is /var/lib/libvirt/images/routeros/00cb/template/ 
#### Relevant stacktraces
https://be-gen-1.demo.greenitglobe.com/grid/job?id=d1aa187a611440cba9312ef828043d86

```Traceback (most recent call last):
~   File "/opt/jumpscale7/lib/JumpScale/grid/jumpscripts/JumpscriptFactory.py", line 176, in executeInProcess
    return True, self.module.action(*args, **kwargs)
~   File "/tmp/jumpscripts/jumpscale_vfs_migrate_routeros.py", line 55, in action
    j.system.btrfs.snapshot(templatepath, destination)
~   File "/opt/jumpscale7/lib/JumpScale/lib/btrfs/BtrfsExtension.py", line 47, in snapshot
    self.__btrfs(*cmd)
~   File "/opt/jumpscale7/lib/JumpScale/lib/btrfs/BtrfsExtension.py", line 28, in __btrfs
    raise RuntimeError(err)
~ RuntimeError: ERROR: cannot snapshot '/var/lib/libvirt/images/routeros/template/': File exists
```
#### Installation information
```
JumpScale
Core: tag: v7.2.6 (8a77511) 1/23/2018, 3:15:23 PM
Portal: branch: production (ada4a21) 1/30/2018, 7:44:31 PM
OpenvCloud
Core: branch: production (a5c4eee) 2/14/2018, 1:32:38 PM
G8VDC: tag: v2.2.6 (989668b) 12/27/2017, 4:19:04 PM
Selfhealing: branch: production (3bc2f9b) 2/7/2018, 1:58:11 PM
OpenvStorage be-gen-1
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.0-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
```

**Comment by Pishoy** [comment]
https://docs.greenitglobe.com/gig/proj_gig_belgium/issues/60

**Comment by grimpy** [comment]
Fixed part of https://github.com/0-complexity/openvcloud/pull/1443

**Comment by ahmedelsayed-93** [comment]
```
JumpScale
Core: branch: master (f316dcf) 3/15/2018, 11:06:22 AM
Portal: branch: master (6012e26) 4/2/2018, 7:40:00 PM
OpenvCloud
Core: branch: master (565678e) 4/10/2018, 8:55:35 AM
G8VDC: branch: master (b085672) 3/16/2018, 5:09:29 PM
Selfhealing: branch: master (7e92f5a) 4/3/2018, 10:33:53 AM
OpenvStorage se-gen-1
openvstorage-backend-core: 1.9.2-1
openvstorage-health-check: 3.4.8-1
openvstorage-webapps: 2.9.12-1
openvstorage-backend-webapps: 1.9.2-1
openvstorage-core: 2.9.12-1
openvstorage-hc: 1.9.2-1
alba-ee: 1.5.26
openvstorage: 2.9.12-1
openvstorage-backend: 1.9.2-1
openvstorage-extensions: 0.1.2-1
openvstorage-sdm: 1.9.1-1
````
