### ISSUE TITLE
Internal server error when opening certain ecos

### ISSUE THREAD

**Issue by grimpy** [0-complexity/openvcloud#1596]
#### Detailed description

When trying to open an eco with the followign text portal generate internal server error
```
Traceback (most recent call last):                                                                                             
~   File "/tmp/jumpscripts/cloudscalers_deployment_test.py", line 284, in action                                                     
    vmachine = get_create_vm(stack, cloudspace, image['id'])                                                                   
~   File "/tmp/jumpscripts/cloudscalers_deployment_test.py", line 126, in get_create_vm                                         
    vmachine = pcl.actors.cloudapi.machines.get(vmachineId)                                                                    
~   File "/opt/jumpscale7/lib/JumpScale/portal/portal/PortalClient.py", line 43, in __getattribute__                            
    actor = self._client.getActor(self._appname, actorname)                                                                    
~   File "/opt/jumpscale7/lib/JumpScale/portal/portal/PortalClient.py", line 87, in getActor                                    
    result = self.wsclient.callWebService("system", "contentmanager", "prepareActorSpecs", app=appname, actor=actorname)        
~   File "/opt/jumpscale7/lib/JumpScale/portal/portal/PortalClientWS.py", line 73, in callWebService                           
    result = self.httpconnection.post(url, headers=headers, data=data)                                                         
~   File "/opt/jumpscale7/lib/JumpScale/baselib/http_client/HttpClient.py", line 92, in post                                   
    response = self._http_request(url, data=data, headers=headers, method='POST',**params)                                     
~   File "/opt/jumpscale7/lib/JumpScale/baselib/http_client/HttpClient.py", line 177, in _http_request                          
    raise HTTPError(e, url)                                                                                                    
~ HTTPError: None:                                                                                                             
 Could not open http connection to url https://gergergergig.tech:443/restmachine/system/contentmanager/prepareActorSpecs?authkey=rgerger
```
                                                                                                                              

#### Relevant stacktraces

```
Traceback (most recent call last):                                                                                                      
  File "/opt/jumpscale7/lib/gevent/pywsgi.py", line 508, in handle_one_response                                                         
    self.run_application()                                                                                                              
  File "/opt/jumpscale7/lib/gevent/pywsgi.py", line 494, in run_application                                                             
    self.result = self.application(self.environ, self.start_response)                                                                   
  File "/opt/jumpscale7/lib/beaker/middleware.py", line 155, in __call__                                                                
    return self.wrap_app(environ, session_start_response)                                                                               
  File "/opt/jumpscale7/lib/JumpScale/portal/portal/auth.py", line 52, in __call__                                                      
    result = self.app(env, my_response)                                                                                                 
  File "/opt/jumpscale7/lib/JumpScale/portal/portal/PortalServer.py", line 50, in wrapper                                               
    result = func(self, env, start_response)                                                                                            
  File "/opt/jumpscale7/lib/JumpScale/portal/portal/PortalServer.py", line 1243, in router                                              
    pagestring = str(self.returnDoc(ctx, space, pagename, {}))                                                                          
  File "/opt/jumpscale7/lib/JumpScale/portal/portal/PortalServer.py", line 534, in returnDoc                                            
    return doc.getHtmlBody(paramsExtra=extraParams, ctx=ctx)                                                                            
  File "/opt/jumpscale7/lib/JumpScale/portal/docpreprocessor/Doc.py", line 220, in getHtmlBody
    page = ws.confluence2htmlconvertor.convert(content, doc=self, requestContext=ctx, page=ws.getpage(), paramsExtra=ctx.params)
  File "/opt/jumpscale7/lib/JumpScale/portal/docgenerator/Confluence2HTML.py", line 482, in convert
    from JumpScale.core.Shell import ipshell
ImportError: cannot import name ipshell
```

**Comment by grimpy** [comment]
[eco.txt](https://github.com/0-complexity/openvcloud/files/2173735/eco.txt)
this is the full eco which you can import (make sure to change the gid) to test this issue
