### ISSUE TITLE
Recycle bin autotests

### ISSUE THREAD

**Issue by FastGeert** [0-complexity/openvcloud#1601]
Automatically mimic the portal users behavior and validate if things work propwerly regarding the Recylce bin

**Comment by ahmedelsayed-93** [comment]
tests fail
you can found logs in ovc.log file in  http://10.101.107.59:9000/minio/tests-result/53/

**Comment by katia-e** [comment]
After running tests locally OVC-017 is still failing. Account fail to restore, portal pop-up error: `Cannot restore an image on a deleted account`.

Test error:
```
FAIL: OVC-0017                                                                                                                                                                           
----------------------------------------------------------------------                                                                                                                   
Traceback (most recent call last):                                                                                                                                                       
  File "/opt/code/github/0-complexity/openvcloud/tests/ovc_master_hosted/OVC/a_basic/recyclebin_tests.py", line 545, in test017_restore_deleted_account                                  
    self.wait_for_status('CONFIRMED', self.api.cloudapi.accounts.get, accountId=self.account_id)                                                                                         
  File "/opt/code/github/0-complexity/openvcloud/tests/utils/utils.py", line 350, in wait_for_status                                                                                     
    self.assertEqual(resource['status'], status)                                                                                                                                         
AssertionError: u'DELETED' != 'CONFIRMED'   
```
