### ISSUE TITLE
DS1: export on specific machine fails without email notification or error being displayed on the portal

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1641]
Hi, 

  The export on the specific VM fails without giving any further information. 

The logs from the portal container are the following:

```python
10.244.2.123 - - [2018-07-26 14:14:21] "POST /restmachine/cloudapi/machines/exportOVF HTTP/1.0" 200 130 0.945428
Traceback (most recent call last):
  File "/opt/jumpscale7/lib/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/opt/jumpscale7/apps/portals/main/base/cloudapi__machines/methodclass/cloudapi_machines.py", line 495, in syncExportOVF
    volumes = provider.ex_clone_disks(diskmapping, disks_snapshots)
  File "/opt/jumpscale7/libext/CloudscalerLibcloud/compute/drivers/libvirt_driver.py", line 729, in ex_clone_disks
    source_edgeclient, edgeclients = self.getEdgeClientFromVolume(volume)
TypeError: 'NoneType' object is not iterable
<Greenlet at 0x7f75eac78190: <bound method cloudapi_machines.syncExportOVF of <cloudapi_machines.cloudapi_machines object at 0x7f75f1cdc210>>({'passwd': 'mypassword', 'path': 'vm-2970', 'usernam, {
  "_ckey": "",
  "_meta": [
    "osismodel",
 , <CloudscalerLibcloud.compute.drivers.libvirt_drive, {
  "_ckey": "",
  "_meta": [
    "osismodel",
 , u'xxxx@itsyouonline', None)> failed with TypeError

10.244.2.123 - - [2018-07-26 14:14:27] "GET /grid/Jobs HTTP/1.0" 200 48094 0.086882
10.244.2.123 - - [2018-07-26 14:14:29] "GET /restmachine/system/contentmanager/modelobjectlist?
```

**Comment by grimpy** [comment]
The storagenode of the original disk was down (atleast our agent) which caused an internal error, this error can not be avoided but should have been reported better and an email should have been send to the tell the user the export failed
