### ISSUE TITLE
Upgrade is reported failed but panel shows new version as well as new features

### ISSUE THREAD

**Issue by dinosn** [0-complexity/openvcloud#1733]
Hello on ch environment we have this case

```
Identity added: /root/.ssh/id_rsa (/root/.ssh/id_rsa)
Lifetime set to 86400 seconds
Preparing resources
Waiting for stop node to be done...
ch-lug-dc01-001-ctr-01: Stop JumpScale services
ch-lug-dc01-001-ctr-02: Stop JumpScale services
ch-lug-dc01-001-ctr-03: Stop JumpScale services
cpu-01: Stop JumpScale services
cpu-02: Stop JumpScale services
cpu-03: Stop JumpScale services
cpu-04: Stop JumpScale services
cpu-05: Stop JumpScale services
cpu-06: Stop JumpScale services
cpu-07: Stop JumpScale services
cpu-08: Stop JumpScale services
cpu-09: Stop JumpScale services
cpu-10: Stop JumpScale services
cpu-11: Stop JumpScale services
cpu-12: Stop JumpScale services
storage-01: Stop JumpScale services
storage-02: Stop JumpScale services
storage-03: Stop JumpScale services
storage-04: Stop JumpScale services
storage-05: Stop JumpScale services
storage-06: Stop JumpScale services
storage-07: Stop JumpScale services
storage-08: Stop JumpScale services

Restarting cluster...
Deleting configmaps
Write system config
Deleting services
Deleting statefulset
Deleting deployments
Preparing resources
Write system config
Waiting for mongo to be ready..
Waiting for syncthing to be ready..
Waiting for influxdb to be ready..
Waiting for osis to be ready..
Waiting for agentcontroller to be ready..
Waiting for stats-collector to be ready..
Waiting for portal to be ready..
Waiting for pxeboot to be ready..
Waiting for zero-access to be ready..
Waiting for management to be ready..
Waiting for ovs to be ready..
Waiting for controller-jsagent to be ready..
Waiting for nginx to be ready..
Waiting for start node to be done...
ch-lug-dc01-001-ctr-01: Start JumpScale services
ch-lug-dc01-001-ctr-02: Start JumpScale services
ch-lug-dc01-001-ctr-03: Start JumpScale services
cpu-01: Start JumpScale services
cpu-02: Start JumpScale services
cpu-03: Start JumpScale services
cpu-04: Start JumpScale services
cpu-05: Start JumpScale services
cpu-06: Start JumpScale services
cpu-07: Start JumpScale services
cpu-08: Start JumpScale services
cpu-09: Start JumpScale services
cpu-10: Start JumpScale services
cpu-11: Start JumpScale services
cpu-12: Start JumpScale services
storage-01: Start JumpScale services
storage-02: Start JumpScale services
storage-03: Start JumpScale services
storage-04: Start JumpScale services
storage-05: Start JumpScale services
storage-06: Start JumpScale services
storage-07: Start JumpScale services
storage-08: Start JumpScale services
Error when performing node start cpu-08: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-11: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:33 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-03: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-04: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-10: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-06: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-12: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:33 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-01: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-07: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-05: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-09: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 
Error when performing node start cpu-02: ERROR: Cannot execute (ssh):
set -e;bash -c "[ ! -e '/root/.bash_profile' ] && touch '/root/.bash_profile' ;source /root/.bash_profile;ays start"
output:
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
2018/08/23 10:34:33 - atyourserviceAction       - Status jumpscale:redis_system not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:redis_system
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :redis          :system is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:nginx__main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Starting jumpscale:nginx__main
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale      :nginx          :main is running
2018/08/23 10:34:34 - atyourserviceAction       - Status jumpscale:jsagent_main not running
2018/08/23 10:34:34 - atyourserviceAction       - Stopping jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting jumpscale:jsagent_main
2018/08/23 10:34:35 - atyourserviceAction       - Status jumpscale      :jsagent        :main is running
2018/08/23 10:34:35 - atyourserviceAction       - Status openvcloud:vncproxy_main not running
2018/08/23 10:34:35 - atyourserviceAction       - Stopping openvcloud:vncproxy_main
2018/08/23 10:34:35 - atyourserviceAction       - Starting openvcloud:vncproxy_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:vncproxy_main not running

#########   Operational Critical Error    #################
Could not start:openvcloud     :vncproxy       :main, could not connect to ports 8091.
###########################################################

2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud:libvirtlistener_main not running
2018/08/23 10:34:56 - atyourserviceAction       - Stopping openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Starting openvcloud:libvirtlistener_main
2018/08/23 10:34:56 - atyourserviceAction       - Status openvcloud     :libvirtlistener:main is running
errors:
 ((type:runtime.error) 

ERROR:root:Error:
Traceback (most recent call last):
  File "./installer", line 1261, in upgrade_cluster
    cluster.update()
  File "./installer", line 1026, in update
    self.kube_client_apply()
  File "./installer", line 975, in kube_client_apply
    self.apply_template(template_file, kind='deployment')
  File "./installer", line 825, in apply_template
    raise j.exceptions.Timeout('Deploying {} took longer than expected. Exiting..'.format(template_name))
JumpScale9.errorhandling.JSExceptions.Timeout: ERROR: Deploying nginx took longer than expected. Exiting.. ((type:timeout)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./installer", line 1264, in upgrade_cluster
    pnode_action(pnodes, 'start')
  File "./installer", line 172, in pnode_action
    raise RuntimeError("Failed to apply {}".format(action))
RuntimeError: Failed to apply start
Failed to update environment.
```

**Comment by dinosn** [comment]
Closing this is a known case of PEBCAK

**Comment by hofkensj** [comment]
hahahaha - care for a PICNIC ?

**Comment by FastGeert** [comment]
As soon as stor-08 is back, i do advise to run the upgrade procedure once more.

**Comment by dinosn** [comment]
Hello yes it was done twice and there was no issue on the second attempt.
