### ISSUE TITLE
Error on 0-access page in admin portal

### ISSUE THREAD

**Issue by katia-e** [0-complexity/openvcloud#1821]
#### Detailed description
eco: [2b703a6d-2c50-7146-07c8-d0bdd3ba0004](https://be-g8-3.gig.tech/grid/error%20condition?id=2b703a6d-2c50-7146-07c8-d0bdd3ba0004)

![screenshot from 2018-09-19 11-28-07](https://user-images.githubusercontent.com/32639869/45744654-5b713300-bbff-11e8-9cf9-91a72d6d6d8d.png)

#### Steps to reproduce
[https://be-g8-3.gig.tech/cbgrid/0-access](https://be-g8-3.gig.tech/cbgrid/0-access)

#### Relevant stacktraces
`/opt/jumpscale7/lib/requests/adapters.py`

``` py
Traceback (most recent call last):
~   File "/opt/jumpscale7/lib/JumpScale/portal/portal/MacroExecutor.py", line 365, in executeMacroOnContent
    paramsExtra=paramsExtra, cmdstr=cmdstr, requestContext=ctx, content=content, page=page)
~   File "/opt/jumpscale7/lib/JumpScale/baselib/taskletengine/TaskletEngine.py", line 112, in executeV2
    return self.taskletEngines[groupname].executeV2(**args)
~   File "/opt/jumpscale7/lib/JumpScale/baselib/taskletengine/TaskletEngine.py", line 251, in executeV2
    params = tasklet.checkExecuteV2(args, params, tags)
~   File "/opt/jumpscale7/lib/JumpScale/baselib/taskletengine/TaskletEngine.py", line 54, in checkExecuteV2
    params = self.module.main(j, args, params, tags, self)
~   File "/opt/jumpscale7/apps/portals/main/base/CBGrid/.macros/wiki/accesssessions/3_accesssessions.py", line 25, in main
    remote=remote, ctx=args.requestContext
~   File "/opt/jumpscale7/apps/portals/main/base/cloudbroker__zeroaccess/methodclass/cloudbroker_zeroaccess.py", line 55, in listSessions
    headers={"Authorization": "Bearer {jwt}".format(jwt=jwt)},
~   File "/opt/jumpscale7/lib/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
~   File "/opt/jumpscale7/lib/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
~   File "/opt/jumpscale7/lib/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
~   File "/opt/jumpscale7/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
~   File "/opt/jumpscale7/lib/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
~ ConnectionError: HTTPConnectionPool(host='zero-access', port=5000): Max retries exceeded with url: /sessions?query=&user= (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fa803c1e290>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

#### Installation information
- environment: be-g8-3
- ovc version: master (update time 9/19/2018, 9:17:25 AM)

    openvstorage-backend-core: 1.9.2-1
    openvstorage-health-check: 3.4.8-1
    openvstorage-webapps: 2.9.12-1
    openvstorage-backend-webapps: 1.9.2-1
    openvstorage-core: 2.9.12-1
    openvstorage-hc: 1.9.2-1
    alba-ee: 1.5.26
    openvstorage: 2.9.12-1
    openvstorage-backend: 1.9.2-1
    openvstorage-extensions: 0.1.2-1
    openvstorage-sdm: 1.9.1-1

**Comment by FastGeert** [comment]
Looks like the 0-access pod was not running.
