### ISSUE TITLE
Fail to restore cloudspace from Recycle Bin

### ISSUE THREAD

**Issue by katia-e** [0-complexity/openvcloud#1866]
#### Detailed description
Fail to restore a cloudspace from Recycle Bin. Fails with error `Failed to start vfw`
error condition [01f5df7d-bdd7-edf2-1b5d-1490c84fcff1](https://be-g8-3.gig.tech/grid/error%20condition?id=01f5df7d-bdd7-edf2-1b5d-1490c84fcff1)

#### Relevant stacktraces

``` py
Traceback (most recent call last):
~   File "/opt/jumpscale7/lib/JumpScale/grid/jumpscripts/JumpscriptFactory.py", line 191, in executeInProcess
    return True, self.module.action(*args, **kwargs)
~   File "/tmp/jumpscripts/jumpscale_vfs_start_routeros.py", line 27, in action
    vlan = fwobject["vlan"]
~ KeyError: 'vlan'
```

**Comment by katia-e** [comment]
still fail to restore cloudspace with error mesage `Failed to start vfw`

**Comment by katia-e** [comment]
After last update restore of a cloudspace succeeded ones and failed when deleting restoring again.
stacktrace:
``` py
Traceback (most recent call last):
~   File "/opt/jumpscale7/lib/JumpScale/grid/jumpscripts/JumpscriptFactory.py", line 191, in executeInProcess
    return True, self.module.action(*args, **kwargs)
~   File "/tmp/jumpscripts/jumpscale_vfs_start_routeros.py", line 72, in action
    protect_interfaces(network, dom)
~   File "/tmp/jumpscripts/jumpscale_vfs_start_routeros.py", line 31, in protect_interfaces
    for publicip in fwobject["pubips"]:
~ KeyError: 'pubips'
```
