### ISSUE TITLE
Error when creating new cloudspace

### ISSUE THREAD

**Issue by katia-e** [0-complexity/openvcloud#1874]
#### Detailed description
Error when creating new cloudspace

Node: cpu-06
Jumpscript: `vfs_create`
[job?id=648fa23574bd4c6ca023388d3faee2fb](https://be-g8-3.gig.tech/grid/job?id=648fa23574bd4c6ca023388d3faee2fb)

#### Relevant stacktraces
```py
Traceback (most recent call last):
~   File "/opt/jumpscale7/lib/JumpScale/grid/jumpscripts/JumpscriptFactory.py", line 191, in executeInProcess
    return True, self.module.action(*args, **kwargs)
~   File "/opt/jumpscale7/apps/processmanager/jumpscripts/vfw/vfs_create.py", line 20, in action
    gateway.start()
~   File "/opt/jumpscale7/libext/CloudscalerLibcloud/gateway/__init__.py", line 78, in start
    self._prepare_bundle("dnsmasq")
~   File "/opt/jumpscale7/libext/CloudscalerLibcloud/gateway/__init__.py", line 107, in _prepare_bundle
    j.system.fs.copyDirTree(templatepath, servicepath)
~   File "/opt/jumpscale7/lib/JumpScale/core/system/fs.py", line 408, in copyDirTree
    raise RuntimeError('Source path %s in system.fs.copyDirTree is not a directory'% src)
~ RuntimeError: Source path /var/lib/runc/templates/dnsmasq in system.fs.copyDirTree is not a directory

```

**Comment by katia-e** [comment]
This error was caused due to creation of CS as virtual gateway. Default option should be set to Router OS.
