### ISSUE TITLE
missing Repo: openvcloud_ays.git

### ISSUE THREAD

**Issue by rainmanh** [0-complexity/openvcloud#846]
bash  scripts/install/01-scratch-openvloud.sh 

```
cd /opt/code/github/0-complexity;git -c http.sslVerify=false clone --depth=1 --single-branch -b 2.0 git@github.com:0-complexity/openvcloud_ays.git /opt/code/github/0-complexity/openvcloud_ays
</snip>
+ ays mdupdate
WARNING: no system redis found (port 9999, needs to be installed as instance 'system').
git clone git@github.com:0-complexity/openvcloud_ays.git -> /opt/code/github/0-complexity/openvcloud_ays
cd /opt/code/github/0-complexity;git -c http.sslVerify=false clone --depth=1 --single-branch -b 2.0 git@github.com:0-complexity/openvcloud_ays.git /opt/code/github/0-complexity/openvcloud_ays
E:Cloning into '/opt/code/github/0-complexity/openvcloud_ays'...
E:OpenSSL version mismatch. Built against 1000207f, you have 1000106f
E:fatal: Could not read from remote repository.
E:
E:Please make sure you have the correct access rights
E:and the repository exists.
Traceback (most recent call last):
~   File "/usr/local/bin/ays", line 252, in <module>
    services = getServices(args, filterRemote=args.local, parent=args.parent, precise=args.immediate, hrdReset=args.hrdreset)
~   File "/usr/local/bin/ays", line 175, in getServices
    services = j.atyourservice.findServices(args.domain, args.name, args.instance, parent=parent, precise=precise, hrdReset=hrdReset)
~   File "/opt/jumpscale7/lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 229, in findServices
    self._doinit()
~   File "/opt/jumpscale7/lib/JumpScale/baselib/atyourservice/AtYourServiceFactory.py", line 66, in _doinit
    dest=j.do.pullGitRepo(url,dest=None,login=login,passwd=passwd,depth=1,ignorelocalchanges=False,reset=False,branch=branch, tag=tag)
~   File "/opt/jumpscale7/lib/JumpScale/InstallTools.py", line 1567, in pullGitRepo
    self.execute(cmd,timeout=600)
~   File "/opt/jumpscale7/lib/JumpScale/InstallTools.py", line 1050, in execute
    raise RuntimeError("Could not execute cmd:\n'%s'\nerr:\n%s"%(command,err))
~ RuntimeError: Could not execute cmd:
'cd /opt/code/github/0-complexity;git -c http.sslVerify=false clone --depth=1 --single-branch -b 2.0 git@github.com:0-complexity/openvcloud_ays.git /opt/code/github/0-complexity/openvcloud_ays --depth 1'
err:
Cloning into '/opt/code/github/0-complexity/openvcloud_ays'...
OpenSSL version mismatch. Built against 1000207f, you have 1000106f
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.



```
Where is that repo? or on it's defect, which repo replace that one?

**Comment by despiegk** [comment]
we are sorry you got into this situation, ays is our installation framework but that one is not usable yet on hardware env other then our own so we did not opensource it yet.
If you want to play with our software we suggest you contact any of our guys and see with them how you can do so.
If you want to play with the opensource bits suggest to start with g8os (see github) & jumpscale (just releasing v9, unstable still !!!)

**Comment by rainmanh** [comment]
Hey @despiegk , 
Many thanks for your quick reply.

Given the amount of repositories you people got around, it was a bit difficult to know which one was the right one to look into, a bit of a confusion there.

I have also been looking into the jumpscale8 and currently having conversations with @xmonader about it. (I raised a ticket for you in that project as well)
Again, many thanks for your reply clarifying the situation repo/project related, that clearly sheds a light on this.
And I would love to know what v9 is coming with! 😄 

Thanks
